name: "Generate Documentation"
description: "Generates documentation from defined data files"
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Generate docs
      id: generate_docs
      shell: bash
      run: |
        set -x
        $(python ${{ github.action_path }}/generate-docs.py)
