name: Validate Schemas

on: 
  push:

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyYAML==6.0.1
          pip install jsonschema==4.18.4
      - name: Validate
        uses: ./.github/actions/validate-definitions
